name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop and Remove Old Docker Container
        run: |
          # Stop and remove the container if it exists
          if [ "$(sudo docker ps -a -q -f name=hello-world-flask-app)" ]; then
            sudo docker stop hello-world-flask-app
            sudo docker rm hello-world-flask-app
          fi
      - name: Pull Docker Image
        run: sudo docker pull harshkishorgn/hello-world-flask-app:latest
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:3000 --name hello-world-flask-app harshkishorgn/hello-world-flask-app
