name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t harshkishorgn/hello-world-flask-app:latest .
          docker push harshkishorgn/hello-world-flask-app:latest

      # - name: SSH into EC2 and pull the latest Docker image
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      #     port: ${{ secrets.EC2_SSH_PORT }}
      #     script: |
      #       docker pull your-docker-hub-username/your-repo-name:latest
      #       docker-compose -f /path/to/your/docker-compose.yml up -d

